Implement card for team overview
ms-club-sliit/minihackathon-2022 pull request #25
Opened 2022-06-02 18:17 UTC by ChathurikaThathsarani

2022-06-02 23:48 UTC, miyurugunarathna requested changes
Also you can rename TeamView.jsx as index.jsx. When you have a separate folder for it, no need to use name again. And please attach a screenshot of the UI in PR.

2022-06-02 23:48 UTC, miyurugunarathna commented on src/App.js
> +import TeamCard from "./components/TeamCard/TeamCard";
Don’t import directly. Import it through component index. It’s easier to manage look nice.

2022-06-02 23:48 UTC, miyurugunarathna commented on src/components/TeamCard/TeamCard.jsx
> +export default function TeamCard() {
Make it as an arrow function.

2022-06-04 14:12 UTC, rusiruavb commented
@ChathurikaThathsarani please resolve the conflicts

2022-06-05 04:47 UTC, miyurugunarathna approved these changes
LGTM

2022-06-05 04:50 UTC, merged